### PR TITLE
Packet alignment

### LINKED ISSUE #33: Packet copies can cause undefined behavior
The way HSS uses memcpy can cause issues when copying between different machines. This is necessary to address before upstreaming. 

From the C99 standard
>   6.5.3.2 Address and indirection operators
>    87) Among the invalid values for dereferencing a pointer by the unary * operator are a null pointer, an address inappropriately aligned for the type of object pointed to, and the address of an object after the end of its lifetime.

In practice x86 does not care nor would [our version of ARM](https://developer.arm.com/documentation/dui0472/m/compiler-command-line-options/--unaligned-access----no-unaligned-access), but other architectures like [SPARC](https://stackoverflow.com/questions/8568432/is-gccs-attribute-packed-pragma-pack-unsafe) or older ARM chips will.

Take this struct (this a bug that I forgot to update when family went from 1 to 2 bytes).
```
struct hss_payload_connect_ip {
	enum hss_family	family; /* 2 bytes */
	__u8					resvd; /* One byte */
/* Any sane compiler will place another 1 byte pad here */
	__le16					port;
/* Padding here? */
	union hss_payload_connect_ip_addr	addr;
};
```

1. Structs are not packed so the compiler can add padding. Most systems would probably pad this the same way but that's not a guarantee. Between `port` and `addr` a 64-bit system may want to align to 8 byes and insert another 4-byte pad where a 32-bit system probably won't.
2. Packing the structs is not a solution, [it is undefined behavior to de-reference a misaligned pointer](https://developer.apple.com/documentation/xcode/diagnosing_memory_thread_and_crash_issues_early/misaligned_pointer) and we would have to take special care to design structs not to be misaligned. Thats just a way to introduce problems
3. The way we transmit packets pays no attention to alignment. It occurs to me that this might be why no one else in the kernel typecasts a struct on circular buffer segment. 

The solution is to stop trying to entangle our defined format with the C structs. The members should match up in width and endianness, but memcpy needs to be used instead of typecasting and named assignments. I do not think this will have a performance hit, it's just tedious.

### PR DESCRIPTION
**Pull request by dberliner**
These are the changes I've had sitting for a while. There is still a little work to be done but this is very close, if there's any higher level concerns this would be a good time to address them. 

I still have a few bugs written down that I need to investigate, do more testing and figure out why `Expand buffers to avoid URB error -75` suddenly became necessary when it wasn't before. 

Fixes #33

### CODE REVIEW

File: host/src/hss.h [hunk 1]
```diff
@@ -297,10 +307,131 @@ static inline struct hss_payload_open *hss_get_payload_open(struct hss_packet *p
...
+		size_t cnt = 0; \
+		__u16 family; \
+ \
+		_hss_packet_##dir##_buf(buf, &pkt->hdr.opcode, cnt, 1); \
+		_hss_packet_##dir##_buf(buf, &pkt->hdr.msg_id, cnt, 1); \
+		_hss_packet_##dir##_buf(buf, &pkt->hdr.sock_id, cnt, 1); \
+		_hss_packet_##dir##_buf(buf, &pkt->hdr.payload_len, cnt, 1); \
+ \
+		if (payload_fields) { \
+			family = le16_to_cpu(pkt->hdr.opcode); \
```
Comment (dberliner) [inline host/src/hss.h:468]: This value will always be system-endian after the above call

File: host/src/hss-proxy.c [hunk 2]
```diff
@@ -415,12 +415,23 @@ void hss_proxy_rcv_cmd(struct hss_packet *packet,
 	struct hss_proxy_context *proxy_ctx =
 		(struct hss_proxy_context *) context;
 
-	newwork = kmalloc(sizeof(struct work_data_t) + packet_len, GFP_ATOMIC);
+	/* Allocate for a work_data_t that can fit the largest possible CMD packet */
+	newwork = kmalloc(sizeof(struct work_data_t) + 52, GFP_ATOMIC);
```
Comment (dberliner) [inline host/src/hss-proxy.c:423]: Dont use a magic number

File: host/src/hss-usb.c [hunk 3]
```diff
@@ -239,7 +239,7 @@ static void hss_read_cmd_callback(struct urb *urb)
 	struct usb_hss *dev = urb->context;
 
 	if (urb->status == 0) {
-		hss_proxy_rcv_cmd((void *)dev->cmd_in_buffer,
+		hss_proxy_rcv_cmd((char *)dev->cmd_in_buffer,
```
Comment (dberliner) [inline host/src/hss-usb.c:242]: Should this be typecast or already a `char *`

**Review by drbild — APPROVED** [review]
